import{z,t,p,m,u,y,h,v,x,A,B}from"./common.js";function C(a,b,d){let c=z(a,b);t(p(m(new u(a.g),c)),e=>{e=y(c,e);h(e)||d.O(e)})}function aa(a,b,d){chrome.storage.onChanged.addListener((c,e)=>{if("sync"===e)for(let f in c){c=v(a,f);if(e=!h(c))a:{e=b;c=x(c);e=x(e);let g=c.length,n=e.length;if(g>n)e=!1;else{for(let l=0;l<g;l++)if(c[g-l]!==e[n-l]){e=!1;break a}e=!0}}if(e){C(a,b,d);break}}})}function D(a){chrome.runtime.openOptionsPage();a.stopImmediatePropagation()}const E=document.getElementsByClassName("gear")[0],
F=document.getElementsByClassName("shadows_10_bf_Class")[0],G=document.getElementsByClassName("gear_wrapper")[0];function ba(a){0===a.button&&G.classList.add("active")}function ca(){G.classList.remove("active")}function da(a){a.preventDefault()}E.addEventListener("mousedown",ba);E.addEventListener("click",D);F.addEventListener("mousedown",ba);F.addEventListener("click",D);G.addEventListener("mouseleave",ca);G.addEventListener("mouseup",ca);G.addEventListener("dragstart",da);G.addEventListener("selectstart",
da);var H=chrome.i18n.getMessage;function I(a,b){var d=document.createRange();d.selectNodeContents(a);d.deleteContents();b=b.split("\n");d=document.createTextNode(b[0]);a.appendChild(d);for(let c=1,e=b.length;c<e;c++)a.appendChild(document.createElement("br")),d=document.createTextNode(b[c]),a.appendChild(d)}function J(a,b){a.g=a.m.g*b/2;ea(a.m,a.g)}function fa(a,b){b=a.g+(b-a.h)/.9;return 0>b?0:b>a.m.g?a.m.g:b}var ia=class{constructor(a){this.m=a;this.g=0;this.A=!1}handleEvent(a){if(0===a.button)switch(a.type){case "mousedown":if(a.target!==
this.m.o){this.A=!1;const d=this.m.g;var b=this.g/d;a=a.offsetX/d;b=2/3<b?.25>=a?0:a<=2/3?1:2:b<1/3?.75<=a?2:a>=1/3?1:0:a<=1/3?0:a>=2/3?2:1;10<=Math.abs(this.m.g*b/2-this.g)&&(J(this,b),ha(this,b));break}this.A=!0;this.h=a.pageX;break;case "mousemove":if(!this.A)break;ea(this.m,fa(this,a.pageX));break;case "mouseup":case "mouseleave":this.A&&(b=Math.round(2*fa(this,a.pageX)/this.m.g),J(this,b),ha(this,b),this.A=!1)}}};function ea(a,b){let d=String(b);a.D.setAttribute("width",d);a.N.setAttribute("width",
d);a.o.style.left=String(b-6)+"px";a.D.style.fill=`hsl(${40+60*b/a.g}, 88.6%, 51.8%)`}function ja(a,b){a.F.addEventListener("mousedown",b);a=document.documentElement;a.addEventListener("mousemove",b);a.addEventListener("mouseup",b);a.addEventListener("mouseleave",b)}var ka=class{constructor(a){this.h=a;this.g=parseFloat(this.h.getElementsByClassName("progress-background_rect")[0].getAttribute("width"));this.D=this.h.getElementsByClassName("progress-left-background_rect")[0];this.N=this.h.getElementsByClassName("progress-left-transparent-border_rect")[0];
this.F=this.h.getElementsByClassName("progress")[0];this.o=this.h.getElementsByClassName("indicator_dot")[0];this.i=this.h.getElementsByClassName("label")[0]}disable(){this.h.classList.add("disabled")}};function ha(a,b){let d=1===b!==(a.B!==a.u);0===b&&a.B||2===b&&!a.B?(a.u=!a.B,A(a.M,a.C,a.u)):d&&(a.u=!a.u,a.H.K(a.u));la(a)}function ma(a){a.A=!1;J(a,0);var b=H("cannot_run");I(a.m.i,b);a.m.disable();a.m.F.removeEventListener("mousedown",a);b=document.documentElement;b.removeEventListener("mousemove",
a);b.removeEventListener("mouseup",a);b.removeEventListener("mouseleave",a)}function na(a){var b=a.B;b=b===a.u?b?2:0:1;a.A=!1;J(a,b);la(a)}function la(a){var b=H(a.B?a.u?"enabled":"temp_disabled":a.u?"temp_enabled":"disabled");I(a.m.i,b)}var pa=class extends ia{constructor(a,b,d,c){super(a);this.M=b;this.H=d;this.L=e=>{chrome.runtime.lastError?(ma(this),oa(this.H,f=>{f&&(f=H("pending_refresh"),I(this.m.i,f))})):(this.u=e,h(this.B)||na(this))};c?.startsWith("http")?(this.C=(new URL(c)).hostname,ja(a,
this),C(b,this.C,this),this.H.J(this.L),aa(b,this.C,this)):ma(this)}O(a){this.B=a;h(this.u)||this.H.J(this.L)}};function oa(a,b){qa(a.g.id,()=>{b(!chrome.runtime.lastError)})}class ra{constructor(a){this.g=a}}var ta=class extends ra{K(a){chrome.tabs.sendMessage(this.g.id,a?0:1)}J(a){chrome.tabs.sendMessage(this.g.id,4,sa,a)}},ua=class extends ra{K(a){chrome.tabs.sendMessage(this.g.id,a?2:3)}J(a){chrome.tabs.sendMessage(this.g.id,5,sa,a)}};const sa={frameId:0};document.querySelectorAll("[data-locale]").forEach(function(a){let b=
H(a.dataset.locale);I(a,b)});function qa(a,b){chrome.tabs.executeScript(a,{code:""},b)}chrome.tabs.query({active:!0,lastFocusedWindow:!0},([a])=>{const b=new B("sync","JS2."),d=new B("sync","CSS."),[c,e]=document.getElementsByClassName("tile"),f=new ka(c),g=new ka(e),n=new ua(a);new pa(f,b,new ta(a),a?.url);new pa(g,d,n,a?.url)});
// Copyright 2021-2022, Sean Lee <i73hi64d0wr5df8pckig@gmail.com>. All rights reserved.