import{m,u,t,x,h,B,p,v,A}from"./common.js";function va(a,b){b=a.i(b);a=m(new u(a.g),[b]);a.i.push(2);t(a)}function wa(a,b,d){let c=0,e=a.length;for(;c<e;){let f=(c+e)/2|0,g=d(a[f],b);if(0===g)return f;0>g?c=f+1:e=f}return-c-1}let xa=document.createNodeIterator(document.body,128),K,L,ya=chrome.i18n.getMessage;for(;K=xa.nextNode();){L=K.data;let a=L.indexOf("$");-1===a?K.before(document.createTextNode(ya(L))):K.previousElementSibling.setAttribute(L.slice(0,a),ya(L.slice(a+1)))}function Aa(a,b){return`<td><span class="switch-root${b?
" inherited":""}"><span class="switch-buttonBase${a?" checked":""}"><span class="switch-button"><input class="switch-input" type="checkbox"><span class="switch-thumb"></span></span><span class="switch-touchRipple"></span></span><span class="switch-track"></span></span></td>`}function M(a){let {v:b,l:d,j:c}=a;a=0!==(d&1);let e=0!==(d&2),f=0!==(c&1),g=0!==(c&2);return`<tr><td>${b||"("+chrome.i18n.getMessage("default")+")"}</td><td>${b?'<div class="trash-button-base circle clickable"><img src="./assets/svg/garbage-can.svg" width="17" height="17"></div>':
""}</td>${Aa(a,e)}${Aa(f,g)}</tr>`}function Ba(a,b){a.firstElementChild.classList.toggle(Ca,0!==(b&1));a.classList.toggle(Da,0!==(b&2))}function Ea(a,b){a=x(N(a));let d=a.length,c=b.length;for(let e=1;;e++){let f=a[d-e],g=b[c-e];if(h(f))return h(g)?0:-1;if(h(g))return 1;if(f<g)return-1;if(f>g)return 1}}function N(a){a=a.firstElementChild.textContent;a.startsWith("(")&&(a="");return a}var Ca="checked",Da="inherited";const Fa={v:"",l:null,j:null};function Ga(a,b){return a.h<b?-1:a.h>b?1:0}function O(a,
b){"l"in b&&(a.s.l=b.l);"j"in b&&(a.s.j=b.j)}function P(a,b){let d=a.h;b.v&&(d+="."+b.v);var c=a.s.l;a=a.s.j;return{v:d,l:null==c?b.l|2:c?1:0,j:null==a?b.j|2:a?1:0}}function Ha(a,b,d){let {I:c,G:e}=Ia(a,x(b),Fa);O(c,d);return{I:c,G:P(c,e)}}function Q(a,b){let d=b.pop();return h(d)?a:Q(Ja(a,d),b)}function Ja(a,b){let d=wa(a.g,b,Ga);if(0<=d)return a.g[d];b=new Ka(b);a.g.splice(-d-1,0,b);return b}function Ia(a,b,d){let c=b.pop();return h(c)?{I:a,G:d}:Ia(Ja(a,c),b,P(a,d))}function*R(a,b){h(a.s.l)&&h(a.s.j)||
(yield b);for(let d of a.g)yield*R(d,P(d,b))}var Ka=class{constructor(a){this.h=a;this.s={l:void 0,j:void 0};this.g=[]}};const S=new B("sync","JS2."),T=new B("sync","CSS.");function La(){return new Promise(a=>{t(p(m(new u(chrome.storage.sync),null)),a)})}function Ma(a,b,d){let c,e=v(a.i,b);h(e)?(e=v(a.h,b),h(e)||(c={j:d})):c={l:d};return{C:e,s:c}}function Na(a){var b=U;chrome.storage.onChanged.addListener((d,c)=>{if("sync"===c)for(let [g,n]of Object.entries(d)){d=a;let {C:l,s:za}=Ma(b,g,n.newValue);
if(!h(za)){var {I:e,G:f}=Ha(b.g,l,za);d(l,R(e,f))}}})}const U=new class{constructor(a,b){this.i=a;this.h=b;this.g=new Ka("")}}(S,T);function V(){var a=W;var b=U.g;b=R(b,P(b,Fa));b=Oa(b);let d="";for(let c of b)d+=M(c);a.o.innerHTML=d}function X(a,b,d){let c=wa(a.g,x(b),Ea);b=d&&d.v===b;0>c?(c=-c-1,b?(b=c,h(a.g[b])?a.o.insertAdjacentHTML("beforeend",M(d)):a.g[b].insertAdjacentHTML("beforebegin",M(d))):d&&Y(a,c,d)):b?Y(a,c,d):(a.g[c].remove(),c--);return c}function Y(a,b,d){h(d.l)||Ba(a.g[b].children[2].firstElementChild,
d.l);h(d.j)||Ba(a.g[b].children[3].firstElementChild,d.j)}function Pa(){var a=W,b=Qa;a.i.addEventListener("input",()=>{a.h.classList.contains("search")&&b()})}function Ra(){var a=W,b=Sa;a.i.addEventListener("keypress",d=>{a.h.classList.contains("search")||13===d.keyCode&&b(a.i.value)});a.i.previousSibling.previousSibling.addEventListener("click",()=>{b(a.i.value)})}function Ta(){var a=Ua,b=Va,d=Wa;W.o.addEventListener("click",c=>{c=c.target;c="lookupPrefix"in c?1===c.nodeType?c:c.parentElement:void 0;
if(c)if("INPUT"===c.nodeName&&c.classList.contains("switch-input")){c=c.closest("td");let e=c.parentElement,f=N(e),g=c.firstElementChild.firstElementChild.classList.contains(Ca);c===e.children[2]?b(f,g):d(f,g)}else(c.classList.contains("trash-button-base")||c.parentElement.classList.contains("trash-button-base"))&&a(N(c.closest("tr")))})}const W=new class{constructor(){this.o=document.getElementsByTagName("tbody")[0];this.g=this.o.children;this.h=this.o.parentElement;this.i=this.h.querySelector(".input-row input")}};
(async function(){var a=U,b=await La();for(let c in b){let {C:e,s:f}=Ma(a,c,b[c]);if(!h(f)){var d=f;O(Q(a.g,x(e)),d)}}})().then(()=>{V();Na((a,b)=>{var d=W;b=Oa(b);let {value:c,done:e}=b.next();a=X(d,a,c);if(!e)for(let f of b)Y(d,++a,f)});Ta();Pa();Ra()});function Ua(a){va(S,a);va(T,a);O(Q(U.g,x(a)),{l:void 0,j:void 0});X(W,a)}function Va(a,b){A(S,a,!b)}function Wa(a,b){A(T,a,!b)}function Qa(){V()}function*Oa(a){var b=W;b=b.h.classList.contains("search")?b.i.value:"";for(let d of a)d.v.includes(b)&&
(yield d)}const Xa=/([A-Za-z]+\.)*[A-Za-z]+/;function Sa(a){if(Xa.test(a)){({G:a}=Ha(U.g,a,{l:null,j:null}));var b=a;a=W;b=X(a,b.v,b);a.g[b].scrollIntoView({behavior:"smooth",block:"nearest"})}}window.Search.addEventListener("click",()=>{let a=W.h.classList;a.remove("addNew");a.add("search");V()});window.Add_New.addEventListener("click",()=>{let a=W.h.classList;a.add("addNew");a.remove("search");V()});window.Rate.addEventListener("click",()=>{var a;(a=chrome.runtime.getManifest().update_url)?({hostname:a}=
new URL(a),a=a.endsWith("google.com")?"https://chrome.google.com/webstore/detail/emfeppdfcjnldjgmofdkbggeacapegen/reviews":a.endsWith("microsoft.com")?"https://microsoftedge.microsoft.com/addons/detail/ijopbbfjlehabpldjiaipgiiedhfhbad":a.endsWith("naver.com")?"https://store.whale.naver.com/detail/bdboifadgcmidogceiohgchkmlcicagk/":"https://ultimate-enable-right-click.github.io"):a="https://ultimate-enable-right-click.github.io";window.open(a,"_blank")});document.title=chrome.i18n.getMessage("extName");
window.Help.addEventListener("click",()=>{let a;a="ko"===chrome.i18n.getUILanguage()?"https://github.com/ultimate-enable-right-click/help/blob/master/help-ko.md":"https://github.com/ultimate-enable-right-click/help/blob/master/help-en.md";window.open(a,"_blank")});chrome.runtime.sendMessage({type:2});
// Copyright 2021-2022, Sean Lee <i73hi64d0wr5df8pckig@gmail.com>. All rights reserved.